spring.application.name=educonnect

spring.mongodb.uri = mongodb+srv://krishvora77_db_user:6iBSg1yAvi8ebNe7@educonnect.24r38rg.mongodb.net/educonnect?retryWrites=true&w=majority


# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
# IMPORTANT: Use an App Password, NOT your real Gmail password
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
